import type { JobApplication } from './types';

export const initialApplications: JobApplication[] = [
  {
    id: '1',
    company: 'Innovate Inc.',
    role: 'Senior Frontend Developer',
    jobDescriptionUrl: 'https://example.com/job/1',
    location: 'Remote',
    status: '2nd Interview',
    dateApplied: new Date('2024-05-10'),
  },
  {
    id: '2',
    company: 'DataCorp',
    role: 'Data Scientist',
    jobDescriptionUrl: 'https://example.com/job/2',
    location: 'New York, NY',
    status: 'Final Round',
    dateApplied: new Date('2024-05-20'),
  },
  {
    id: '3',
    company: 'Cloud Solutions',
    role: 'DevOps Engineer',
    jobDescriptionUrl: 'https://example.com/job/3',
    location: 'Austin, TX',
    status: 'Applied',
    dateApplied: new Date('2024-06-01'),
  },
  {
    id: '4',
    company: 'HealthWell',
    role: 'Product Manager',
    jobDescriptionUrl: 'https://example.com/job/4',
    location: 'San Francisco, CA',
    status: 'Offer Received',
    dateApplied: new Date('2024-04-15'),
  },
  {
    id: '5',
    company: 'FinTech Group',
    role: 'Backend Engineer',
    jobDescriptionUrl: 'https://example.com/job/5',
    location: 'London, UK',
    status: 'No Offer',
    dateApplied: new Date('2024-05-01'),
  },
    {
    id: '6',
    company: 'E-Commerce World',
    role: 'UX/UI Designer',
    jobDescriptionUrl: 'https://example.com/job/6',
    location: 'Remote',
    status: 'Screening with Recruiter',
    dateApplied: new Date('2024-06-05'),
  },
  {
    id: '7',
    company: 'AI StartUp',
    role: 'Machine Learning Engineer',
    jobDescriptionUrl: 'https://example.com/job/7',
    location: 'Remote',
    status: 'Screening with Recruiter',
    dateApplied: new Date('2024-06-08'),
  },
  {
    id: '8',
    company: 'Gaming Studios',
    role: 'Game Developer',
    jobDescriptionUrl: 'https://example.com/job/8',
    location: 'Tokyo, JP',
    status: 'Rejected CV',
    dateApplied: new Date('2024-05-18'),
  },
  {
    id: '9',
    company: 'SaaS Solutions',
    role: 'Full Stack Developer',
    jobDescriptionUrl: 'https://example.com/job/9',
    location: 'Berlin, DE',
    status: 'Offer Received',
    dateApplied: new Date('2024-04-25'),
  },
];
